[theme]
base = "light"
primaryColor = "#76b900"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f7f7"
textColor = "#1a1a1a"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
